### ISSUE TITLE
Multiple rules reporting errors on the same part

### ISSUE THREAD

**Issue by stramel** [43081j/eslint-plugin-lit#102]
A few rules have overlap with others. Not sure if we would want it to remain like this.

```js
html`<${expr} attr="bar"></${expr}>`
```
![image](https://user-images.githubusercontent.com/855184/119062465-8148ca00-b99c-11eb-9027-abe32c843ec0.png)

```js
html`<x-foo />`
```
![image](https://user-images.githubusercontent.com/855184/119062556-b3f2c280-b99c-11eb-81c0-b7d4fbb375ce.png)

**Comment by 43081j** [comment]
we decided this was ok, since there are some cases you may end up with different rules matching the same position for legitimate reasons.
