### ISSUE TITLE
Add rule to ensure value is bound after min/max

### ISSUE THREAD

**Issue by claviska** [43081j/eslint-plugin-lit#109]
When binding `value` on an input before `min` and `max`, the value is clamped to the default `min` and `max` values, resulting in what appears to be buggy behavior. Note how `value` binds before `min|max`:

[Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtcmFuZ2UnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBwcm9wZXJ0eSgpIHZhbHVlID0gMDtcbiAgQHByb3BlcnR5KCkgbWluID0gMDtcbiAgQHByb3BlcnR5KCkgbWF4ID0gMTAwO1xuICBAcHJvcGVydHkoKSBzdGVwID0gMTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPGlucHV0IHR5cGU9XCJyYW5nZVwiIC52YWx1ZT0ke3RoaXMudmFsdWV9IC5taW49JHt0aGlzLm1pbn0gLm1heD0ke3RoaXMubWF4fSAuc3RlcD0ke3RoaXMuc3RlcH0-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG5cbiAgVGhlIGZvbGxvd2luZyByYW5nZXMgZ28gZnJvbSAtMTAwIHRvIDEwMC48YnI-PGJyPlxuICBcbiAgPHNpbXBsZS1yYW5nZSB2YWx1ZT1cIjBcIiBtaW49XCItMTAwXCIgbWF4PVwiMTAwXCIgc3RlcD1cIjFcIj48L3NpbXBsZS1yYW5nZT4gdmFsdWUgPSAwPGJyPlxuICA8c2ltcGxlLXJhbmdlIHZhbHVlPVwiMTAwXCIgbWluPVwiLTEwMFwiIG1heD1cIjEwMFwiIHN0ZXA9XCIxXCI-PC9zaW1wbGUtcmFuZ2U-IHZhbHVlID0gMTAwPGJyPlxuICA8c2ltcGxlLXJhbmdlIHZhbHVlPVwiLTEwMFwiIG1pbj1cIi0xMDBcIiBtYXg9XCIxMDBcIiBzdGVwPVwiMVwiPjwvc2ltcGxlLXJhbmdlPiB2YWx1ZSA9IC0xMDAgKGluY29ycmVjdCk8YnI-XG4gIFxuICA8c2NyaXB0PlxuICAgIGN1c3RvbUVsZW1lbnRzLndoZW5EZWZpbmVkKCdzaW1wbGUtcmFuZ2UnKS50aGVuKCgpID0-IHtcbiAgICAgIGNvbnN0IHJhbmdlcyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJ3NpbXBsZS1yYW5nZScpO1xuICAgIFxuICAgICAgWy4uLnJhbmdlc10ubWFwKHJhbmdlID0-IHtcbiAgICAgICAgcmFuZ2UudXBkYXRlQ29tcGxldGUudGhlbigoKSA9PiB7XG4gICAgICAgICAgY29uc3QgaW5wdXQgPSByYW5nZS5zaGFkb3dSb290LnF1ZXJ5U2VsZWN0b3IoJ2lucHV0Jyk7XG4gICAgXG4gICAgICAgICAgLy8gTG9nIHJhbmdlIHZhbHVlIGFuZCB0aGUgaW50ZXJuYWwgaW5wdXRzIHZhbHVlXG4gICAgICAgICAgY29uc29sZS5sb2coXG4gICAgICAgICAgICd2YWx1ZSA9ICcgKyByYW5nZS52YWx1ZSwgXG4gICAgICAgICAgICdpbnRlcm5hbCBpbnB1dCB2YWx1ZSA9ICcgKyBpbnB1dC52YWx1ZVxuICAgICAgICAgICk7XG4gICAgXG4gICAgICAgICAgLy8gSGlnaGxpZ2h0IGRpc2NyZXBhbmNpZXNcbiAgICAgICAgICBpZiAocmFuZ2UudmFsdWUgIT09IGlucHV0LnZhbHVlKSB7XG4gICAgICAgICAgICBjb25zb2xlLmVycm9yKCd2YWx1ZXMgZG8gbm90IG1hdGNoJywgcmFuZ2UpO1xuICAgICAgICAgIH1cbiAgICAgICAgfSk7ICAgICAgIFxuICAgICAgfSk7XG4gICAgfSk7XG4gIDwvc2NyaXB0PlxuPC9ib2R5PlxuIn1d)

The last slider is rendered incorrectly, and the internal input has an initial value of `0`. Now let's move the `value` binding _after_ `min|max`:

[Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtcmFuZ2UnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBwcm9wZXJ0eSgpIHZhbHVlID0gMDtcbiAgQHByb3BlcnR5KCkgbWluID0gMDtcbiAgQHByb3BlcnR5KCkgbWF4ID0gMTAwO1xuICBAcHJvcGVydHkoKSBzdGVwID0gMTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPGlucHV0IHR5cGU9XCJyYW5nZVwiIC5taW49JHt0aGlzLm1pbn0gLm1heD0ke3RoaXMubWF4fSAuc3RlcD0ke3RoaXMuc3RlcH0gLnZhbHVlPSR7dGhpcy52YWx1ZX0-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG5cbiAgVGhlIGZvbGxvd2luZyByYW5nZXMgZ28gZnJvbSAtMTAwIHRvIDEwMC48YnI-PGJyPlxuICBcbiAgPHNpbXBsZS1yYW5nZSB2YWx1ZT1cIjBcIiBtaW49XCItMTAwXCIgbWF4PVwiMTAwXCIgc3RlcD1cIjFcIj48L3NpbXBsZS1yYW5nZT4gdmFsdWUgPSAwPGJyPlxuICA8c2ltcGxlLXJhbmdlIHZhbHVlPVwiMTAwXCIgbWluPVwiLTEwMFwiIG1heD1cIjEwMFwiIHN0ZXA9XCIxXCI-PC9zaW1wbGUtcmFuZ2U-IHZhbHVlID0gMTAwPGJyPlxuICA8c2ltcGxlLXJhbmdlIHZhbHVlPVwiLTEwMFwiIG1pbj1cIi0xMDBcIiBtYXg9XCIxMDBcIiBzdGVwPVwiMVwiPjwvc2ltcGxlLXJhbmdlPiB2YWx1ZSA9IC0xMDAgKGluY29ycmVjdCk8YnI-XG4gIFxuICA8c2NyaXB0PlxuICAgIGN1c3RvbUVsZW1lbnRzLndoZW5EZWZpbmVkKCdzaW1wbGUtcmFuZ2UnKS50aGVuKCgpID0-IHtcbiAgICAgIGNvbnN0IHJhbmdlcyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJ3NpbXBsZS1yYW5nZScpO1xuICAgIFxuICAgICAgWy4uLnJhbmdlc10ubWFwKHJhbmdlID0-IHtcbiAgICAgICAgcmFuZ2UudXBkYXRlQ29tcGxldGUudGhlbigoKSA9PiB7XG4gICAgICAgICAgY29uc3QgaW5wdXQgPSByYW5nZS5zaGFkb3dSb290LnF1ZXJ5U2VsZWN0b3IoJ2lucHV0Jyk7XG4gICAgXG4gICAgICAgICAgLy8gTG9nIHJhbmdlIHZhbHVlIGFuZCB0aGUgaW50ZXJuYWwgaW5wdXRzIHZhbHVlXG4gICAgICAgICAgY29uc29sZS5sb2coXG4gICAgICAgICAgICd2YWx1ZSA9ICcgKyByYW5nZS52YWx1ZSwgXG4gICAgICAgICAgICdpbnRlcm5hbCBpbnB1dCB2YWx1ZSA9ICcgKyBpbnB1dC52YWx1ZVxuICAgICAgICAgICk7XG4gICAgXG4gICAgICAgICAgLy8gSGlnaGxpZ2h0IGRpc2NyZXBhbmNpZXNcbiAgICAgICAgICBpZiAocmFuZ2UudmFsdWUgIT09IGlucHV0LnZhbHVlKSB7XG4gICAgICAgICAgICBjb25zb2xlLmVycm9yKCd2YWx1ZXMgZG8gbm90IG1hdGNoJywgcmFuZ2UpO1xuICAgICAgICAgIH1cbiAgICAgICAgfSk7ICAgICAgIFxuICAgICAgfSk7XG4gICAgfSk7XG4gIDwvc2NyaXB0PlxuPC9ib2R5PlxuIn1d)

Now the control renders as expected. Since this isn't obvious, and `value` is often one of the first things users bind to an input, it's probably worth adding a rule to call out when `value` binds _before_ `min` or `max`.

**Comment by stramel** [comment]
This feels more like a bug/quirk with the browsers. When I get on tomorrow, I will do some digging and see if this should be fixed upstream. Might also be a good thing for lit-plugin instead

**Comment by 43081j** [comment]
i wouldn't call it a bug (with browsers or with lit) but agree we should warn people about it.

logically, its the same as:

```ts
const node = document.querySelector('input');

node.value = '40';

node.max = '30'; // this won't change the existing value, it'll just set the new maximum
```

we could have a rule to just check the order is right and `value` comes after everything else.
