### ISSUE TITLE
lit/quoted-expressions match expressions that is not attribute or property

### ISSUE THREAD

**Issue by tevey** [43081j/eslint-plugin-lit#165]
With `"lit/quoted-expressions": ["error", "always"]` in my .eslintrc i expect it to show errors for expressions in properties and attributes without quotes only, but it also shows errors for cases like this:
```
html` <div class="${this.classes.button}">${this.label}</div> `
```
Where it complains that `${this.label}` doesn't have quotes.
![image](https://user-images.githubusercontent.com/1482550/212054533-398afdaa-88a7-40b5-adf3-582ddd2bebb8.png)

**Comment by 43081j** [comment]
ouch thats definitely a bug!

i'll take a look when i can soon
