### ISSUE TITLE
False negative lit/no-classfield-shadowing

### ISSUE THREAD

**Issue by tpluscode** [43081j/eslint-plugin-lit#193]
As I updated the plugin to v1.11, I now have `lit/no-classfield-shadowing` everywhere, for properties declared with `lit@2` decorators

**Comment by 43081j** [comment]
do you have an example?

may be that the rule just doesn't make sense with new decorators, but would have to see an example to be sure

**Comment by tpluscode** [comment]
Here's the smallest I could quickly concoct by extracting the setup from my project: https://gist.github.com/tpluscode/149377e20f27a47ae0e02fdd453f10a7

**Comment by tpluscode** [comment]
`npx eslint element.ts ---quiet` will give you one error from the propety

**Comment by steverep** [comment]
We have the same problem with Home Assistant, except it occurs when upgrading to 1.12.0.  We went from 0 errors to over 6000:

https://github.com/home-assistant/frontend/actions/runs/9081979074/job/24957190667?pr=20775

There was no change to config and deleting cache has no effect.  Note the breakage also affects the `lit/attribute-names` rule.
