### ISSUE TITLE
Add a few CSS rules

### ISSUE THREAD

**Issue by 43081j** [43081j/eslint-plugin-lit#24]
As part of expanding the ruleset to now work over lit's `css` static (which we should be able to access pretty easily now), these rules would be handy:

* `css-deprecated-apply-rule` to detect usages of `@apply`
* `css-deprecated-var-args` to detect usages of `var(--a, --b)` rather than `var(--a, var(--b))`
* `css-host-display` to detect if an element has set its `display` to something
* `css-content-to-slotted` to detect uses of `::content` where we should use `slotted`
* `css-host-hidden` to enforce `:host([hidden])` to be defined

**Comment by stramel** [comment]
My only question is should we spend time implementing the v0 spec to v1 spec changes? I believe most of the deprecated rules are based on https://github.com/Polymer/tools/issues/1051

It may also be worth implementing these in a better language appropriate linting tool, such as `stylelint`.

**Comment by 43081j** [comment]
yup you are right, all of these belong in a stylelint plugin rather than here.

let's leave this for now until we figure what to do about that in general.

**Comment by 43081j** [comment]
Closing this as it will soon be tackled in a separate related plugin.
