### ISSUE TITLE
Rule to check that private property of custom element is not being passed to element

### ISSUE THREAD

**Issue by evangalen** [43081j/eslint-plugin-lit#30]
Just started using LitElement / LitHtml after mainly using AngularJS and Angular 2+ in my previous assignment.

From what I understand, besides properties used to supply data from the caller template you can also define a property that is only used internally in your component.
To indicate that property is internal to the component, I prefixed it's name with a `_` and also added the `private` access modifier to its `@property` decorated field.

Wouldn't it be cool if ESLint lit plugin could lint for property assignment in lit-html templates
that start with `._`?
Or am I doing it all wrong and should I just stop (mis-)using `@property` for private properties?

**Comment by 43081j** [comment]
You are doing the right thing, FYI. Private and protected properties should still be Lit properties (`@property`) if they are to trigger renders internally.

So this is a good idea for a rule as we should easily be able to at least detect setting properties prefixed with `_` on elements.
