### ISSUE TITLE
Add check for illegal escape sequences

### ISSUE THREAD

**Issue by justinfagnani** [43081j/eslint-plugin-lit#44]
See https://github.com/Polymer/lit-html/issues/348

**Comment by 43081j** [comment]
@justinfagnani having looked into this, i guess its as simple as detecting any escaped octal (unless it uses the new `\0oXXX` syntax).

however unfortunately it seems like both the parser eslint uses and babel don't allow this in the first place 🙈  so it would fail lint before it reaches our rule it seems, by an uncaught parser exception..

im not too sure how we can deal with it if thats the case, and it does seem to be.

**Comment by justinfagnani** [comment]
Awesome, thanks @43081j!
