### ISSUE TITLE
Add check for unquoted attribute bindings in self-closing tags.

### ISSUE THREAD

**Issue by justinfagnani** [43081j/eslint-plugin-lit#45]
```js
html`<input .value=${foo}/>`
```

causes problems for the parser. The solution is to add quotes or a space.

**Comment by 43081j** [comment]
Is this only see the end of self closing tags? And out of interest, if that's the case, why is does it only affect those?

Just want to make sure I get the explainer right in the docs when I get around to it

**Comment by justinfagnani** [comment]
@43081j sorry for the delay. Yeah, it's only for self closing tags. The problem is that the `/` is considered part of the attribute value. I think another solution is to make sure there's a space before the `/`.
