### ISSUE TITLE
Ampersand causing false positive

### ISSUE THREAD

**Issue by krumware** [43081j/eslint-plugin-lit#48]
(as discussed on slack)
A line like this:
`<st-card name="S&P 500 Index"></st-card>`

or

`<st-card name="S&amp;P 500 Index"></st-card>`

Causes:
Attribute values may not contain unencoded HTML entities, e.g. use `&gt;` instead of `>`eslint(lit/attribute-value-entities)

**Comment by 43081j** [comment]
The regex is too dumb/catch-all.

we're matching `&` in `&amp;` (my own stupidity).

better to do something like `/([<>"]|&(?![a-z]+;))/`
