### ISSUE TITLE
Add rule to disallow constructor arguments.

### ISSUE THREAD

**Issue by justinfagnani** [43081j/eslint-plugin-lit#82]
We've seen some developers do this when the constructor is never going to be called. It can hide errors elsewhere in the element if that code assume the constructor would have been called with arguments.

**Comment by 43081j** [comment]
Good idea 👍  Do you think this applies to all web components or just lit? Just wondering if it belongs in eslint-plugin-wc or here.

I probably should also update this plugin to recommend or give an option to also pull in the wc plugin.
